# Generated by Django 5.2.6 on 2025-09-14 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='noticia',
            name='resumo',
        ),
        migrations.AddField(
            model_name='noticia',
            name='categoria',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='noticia',
            name='link',
            field=models.URLField(blank=True, help_text='Link externo para a notícia completa', null=True),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='noticias_imagens/'),
        ),
    ]
