# Generated by Django 5.2.6 on 2025-09-14 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0002_remove_noticia_resumo_noticia_categoria_noticia_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='subtitulo',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
