# Generated by Django 5.2.6 on 2025-09-14 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0003_noticia_subtitulo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='noticia',
            name='titulo',
        ),
        migrations.AddField(
            model_name='noticia',
            name='titulo_detalhe',
            field=models.CharField(blank=True, help_text='Título que aparecerá dentro da notícia', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='noticia',
            name='titulo_lista',
            field=models.CharField(blank=True, help_text='Título que aparecerá na lista de notícias', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='imagem',
            field=models.ImageField(blank=True, help_text='Imagem exibida apenas no detalhe', null=True, upload_to='noticias_imagens/'),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='subtitulo',
            field=models.CharField(blank=True, help_text='Subtítulo exibido na página de detalhe', max_length=300, null=True),
        ),
    ]
