# Generated by Django 5.2.6 on 2025-09-15 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0004_remove_noticia_titulo_noticia_titulo_detalhe_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner', models.ImageField(help_text='O banner principal que aparecerá no topo de todas as páginas.', upload_to='site/')),
            ],
        ),
    ]
